networks:
  chat-network:
    driver: bridge

services:
  auth-db:
    image: postgres:15-alpine
    container_name: auth-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: auth_db
    ports:
      - "5435:5432"
    networks:
      - chat-network
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d auth_db"]
      interval: 5s
      retries: 5

  room-db:
    image: postgres:15-alpine
    container_name: room-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: room_db
    ports:
      - "5433:5432"
    networks:
      - chat-network
    volumes:
      - room-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d room_db"]
      interval: 5s
      retries: 5

  chat-db:
    image: postgres:15-alpine
    container_name: chat-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: chat_db
    ports:
      - "5434:5432"
    volumes:
      - chat-db-data:/var/lib/postgresql/data
    networks:
      - chat-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d chat_db"]
      interval: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-broker
    ports:
      - "9093:9093"
    networks:
      - chat-network
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:9092,EXTERNAL://localhost:9093'
      KAFKA_LISTENERS: 'INTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093,EXTERNAL://0.0.0.0:9093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'chat-system-cluster-id'

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8080"
    networks:
      - chat-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-db:5432/auth_db
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - APP_JWT_SECRET=${APP_JWT_SECRET}
    depends_on:
      auth-db:
        condition: service_healthy

  room-service:
    build: ./room-service
    container_name: room-service
    ports:
      - "8082:8080"
    networks:
      - chat-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://room-db:5432/room_db
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - APP_JWT_SECRET=${APP_JWT_SECRET}
    depends_on:
      room-db:
        condition: service_healthy

  chat-service:
    build: ./chat-service
    container_name: chat-service
    ports:
      - "8083:8080"
    networks:
      - chat-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://chat-db:5432/chat_db
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - APP_JWT_SECRET=${APP_JWT_SECRET}
      - ROOM_SERVICE_URL=http://room-service:8080
    depends_on:
      chat-db:
        condition: service_healthy
      kafka:
        condition: service_started

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8084:8080"
    networks:
      - chat-network
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      kafka:
        condition: service_started

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - chat-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: always
    ports:
      - "8090:8080"
    networks:
      - chat-network
    environment:
      - KAFKA_CLUSTERS_0_NAME=chat-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka

volumes:
  auth-db-data:
  room-db-data:
  chat-db-data: