apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: armend03757/chat-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: chat-config
                  key: CHAT_DB_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: chat-secrets
                  key: db-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chat-secrets
                  key: db-password
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: chat-config
                  key: KAFKA_SERVERS
            - name: APP_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: chat-secrets
                  key: jwt-secret
            - name: ROOM_SERVICE_URL
              value: "http://room-service:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  type: LoadBalancer
  selector:
    app: chat-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8080